name: make w.txt

on:
  schedule:
    - cron: '32 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@main
      - name: run aadown.bat
        run: |
          cmd
          cd RMaker
          .\aadown.bat
      - name: commit
        run: |
          git config --global user.name "dd"
          git config --global user.email "aqvm@qq.com"
          git add .
          git commit -m "update" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
