name: make

on:
  schedule:
    - cron: '50 15 * * *'

  workflow_dispatch:

jobs:
  mainrule:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@main
      - name: run mio.bat
        run: |
          cmd
          .\RMaker\mio.bat
      - name: commit
        run: |
          git config --global user.name "dd"
          git config --global user.email "aqvm@qq.com"
          git add .
          git commit -m "规则文件,已在$(date)更新" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  other:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@main
      - name: run bat
        run: |
          cmd
          .\RMaker\other\quantumult.bat
          .\RMaker\other\shadow.bat
      - name: commit
        run: |
          git config --global user.name "dd"
          git config --global user.email "aqvm@qq.com"
          git add .
          git commit -m "规则文件,已在$(date)更新" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
